### ISSUE TITLE
这是一个bug

### ISSUE THREAD

**Issue by ghost** [singod/jeDate#17]
当初始化最小日期（minDate）设置大于“今天”或者最大日期（maxDate）设置小于“今天”，“今天”按钮，逻辑上应该是禁用的。

**Comment by mengrv** [comment]
> 当初始化最小日期（minDate）设置大于“今天”或者最大日期（maxDate）设置小于“今天”，“今天”按钮，逻辑上应该是禁用的。

你解决了吗
