### ISSUE TITLE
使用requirejs加载该组件，会产生bug

### ISSUE THREAD

**Issue by finley0066** [singod/jeDate#19]
我这里遇到个问题，使用require.js模块化加载jeDate，会导致页面一载入自动弹出日历，而后怎么点击input:text都无法开关该日历了。

**Comment by xuancaolinxia** [comment]
我也遇到了这个问题，有解决方法么？

**Comment by finley0066** [comment]
按照以下方案可以解决，已试验
              //if (even) {
        //    jeDt.stopmp(even);
        //    createDiv(doc.body, jeDt.boxCell);
        //    jeDt.elemCell = typeof (opts.dateCell) == "string" ? QD(opts.dateCell)[0] : opts.dateCell;
        //    jeDt.setHtml();
        //} else {
            jeDt.bind(QD(opts.dateCell), "click", function (ev) {
                jeDt.stopmp(ev);
                createDiv(doc.body, jeDt.boxCell);
                jeDt.elemCell = this;
                jeDt.setHtml();
            });
        //};
