### ISSUE TITLE
okfun回调 无法获得elem

### ISSUE THREAD

**Issue by 879584395** [singod/jeDate#31]
function OtherStarTime(elem){
    $.jeDate(elem,{
        insTrigger:false,
        isinitVal: true,
		format: 'hh:mm',
		fixed: true,
		isClear: false,
		ishmsVal: false,
		zIndex: 29,
		okfun: function(elem, val) {
			console.log($(elem)，'无法获取elem')
		},
    });
}

**Comment by singod** [comment]
okfun回调 无法获得elem，问题已经发现，下个版本会修复的
