### ISSUE TITLE
缺少手动重置的方法

### ISSUE THREAD

**Issue by ZinLiao** [singod/jeDate#37]
两个输入框都初始化了时间控件，分为开始时间和结束时间(在一个弹窗里面)，选择时间后手动清空输入框，重新打开弹窗，控件记录的是上次的配置，即使重新配置重新初始化，没有用，建议增加一些手动重置配置的方法

**Comment by Niofh** [comment]
@ZinLeo 这个你解决了吗

**Comment by ZinLiao** [comment]
@Foreverofh 没有
