### ISSUE TITLE
关闭的时候会出现问题，选择框变成NaN-NaN

### ISSUE THREAD

**Issue by bryonliu** [singod/jeDate#4]
jedate.js?1462941863700:430 Uncaught TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.jeDt.dateClose @ jedate.js?1462941863700:430(anonymous function) @ jedate.js?1462941863700:709

**Comment by bryonliu** [comment]
点击页面，页面结构出现变化的时候，回去关闭选择框（即使没有选择框），然后导致Error

**Comment by singod** [comment]
这个问题已经发现了，下个版本就修复了
