### ISSUE TITLE
$.timeStampDate问题

### ISSUE THREAD

**Issue by lazyyman** [singod/jeDate#45]
$.timeStampDate = function (date,bool,format) {
        format = format || 'YYYY-MM-DD hh:mm:ss';
        if(bool == true){  //将时间戳转换成日期
            var setdate = new Date(parseInt(date.substring(0,10)) * 1e3);
            return jet.parse([ setdate.getFullYear(), jet.digit(setdate.getMonth() + 1), jet.digit(setdate.getDate()) ], [ jet.digit(setdate.getHours()), jet.digit(setdate.getMinutes()), jet.digit(setdate.getSeconds()) ], format);
        }else {  //将日期转换成时间戳
            var tmsArr = jet.reMacth(date),
                newdate = new Date(tmsArr[0],tmsArr[1],tmsArr[2],tmsArr[3],tmsArr[4],tmsArr[5]),
                timeStr = newdate.getTime().toString();
            return timeStr.substr(0, 10);
        }
    };

newdate = new Date(tmsArr[0],tmsArr[1],tmsArr[2],tmsArr[3],tmsArr[4],tmsArr[5]),
这个地方的在转换的时候会多增加一个月
tmsArr[1]

**Comment by singod** [comment]
这个问题新版本已经修复了
