### ISSUE TITLE
2处明显BUG，时间戳转换和-30天

### ISSUE THREAD

**Issue by justin107** [singod/jeDate#50]
之前一直用的此插件，都还好，但是最近做项目，发现2处错误，所以指出来

时间戳转换会误差月份，一个月。。。。

减天数的时候，小数字的时候还好，-30天的时候，很明显，今天是8月31日，减去30天居然是7月32日
无奈，自己做了个减法的插进去了。。。

**Comment by singod** [comment]
时间戳转换会误差月份，新版本已经修复了！下个星期会发布新版本！
《减天数的时候，小数字的时候还好，-30天的时候，很明显》 希望您能共享一下您写的代码，非常感谢！

**Comment by justin107** [comment]
var start = {
    format: 'YYYY-MM-DD hh:mm:ss',
    minDate: '2014-06-16 23:59:59', //设定最小日期为当前日期
    isinitVal:true,
    festival:true,
    ishmsVal:false,
    maxDate: $.nowDate({DD:0}), //最大日期
    choosefun: function(elem, val, date){
        end.minDate = date; //开始日选好后，重置结束日的最小日期
        endDates();
    }
};
var end = {
    format: 'YYYY年MM月DD日 hh:mm:ss',
    minDate: $.nowDate({DD:0}), //设定最小日期为当前日期
    festival:true,
    maxDate: '2099-06-16 23:59:59', //最大日期
    choosefun: function(elem, val, date){
        start.maxDate = date; //将结束日的初始值设定为开始日的最大日期
    }
};
以上是官网例子片段，假设今天是8月31号，那么initAddVal:{DD:"-30"}应该是7月31日？
但是start给出的值是7月32日(/ □ \)，-29，-31似乎都没出错，无奈自己写了方法初始开始日期

抱歉才看到回复，希望作者完善这个实用方法，加油
