### ISSUE TITLE
$.nowDate({DD:0})获取今天日期有问题

### ISSUE THREAD

**Issue by dwsmile** [singod/jeDate#56]
今天10月31日，调用$.nowDate()得到结果如下
$.nowDate({DD:0})
"2017-11-01 11:13:18"
$.nowDate({DD:-1})
"2017-10-30 11:13:29"
$.nowDate({DD:+1})
"2017-11-02 11:16:13"

**Comment by zhengybo** [comment]
他这个  计算差  少了一天  ，  再加一个   他在 12 月份的 时候 调用 2017-12-3 调用nowDate 时候  nowDate({DD : 0},'YYYY-MM-DD',2017-12-3) 会直接  变成  2018-00-3  这个 bug   


感觉 这个全是 bug   好多问题

**Comment by singod** [comment]
修复了$.nowDate 在月有31号情况下造成的问题请去官网下载新版的覆盖既可
http://www.jemui.com/uidoc/jedate.html
