### ISSUE TITLE
firefox 下出现问题

### ISSUE THREAD

**Issue by jackPanyj** [singod/jeDate#7]
在firefox中，日期选择框得点俩次才出来。第一次只是填了个当前时间，第二次才出来选择框

**Comment by werts** [comment]
@jackPanyj 你好，我也遇到了这个问题，你怎么解决的呢？

**Comment by jackPanyj** [comment]
@werts 模拟了下，区分浏览器，然后当focus的时候调用下手动调用下click事件

**Comment by werts** [comment]
@jackPanyj 我看了下，应该就是那个window.event搞怪了

**Comment by singod** [comment]
你们这个是旧版本的问题，旧版本的问题不回答，请用最新版本！

**Comment by werts** [comment]
@singod 最新版本又使用了jquery，可惜了
